In [1]:
import pandas as pd

In [6]:
path = "/content/salaries.csv"
df = pd.read_csv(path)

In [7]:
df.head()

  company                  job     degree  salary_more_then_100k
0    Meta      sales executive  bachelors                      0
1    Meta      sales executive    masters                      0
2    Meta     business manager  bachelors                      1
3    Meta     business manager    masters                      1
4    Meta  computer programmer  bachelors                      0

In [14]:
features = df.drop('salary_more_then_100k', axis = 'columns')

In [15]:
target = df["salary_more_then_100k"]

In [16]:
features

      company                  job     degree
0        Meta      sales executive  bachelors
1        Meta      sales executive    masters
2        Meta     business manager  bachelors
3        Meta     business manager    masters
4        Meta  computer programmer  bachelors
5        Meta  computer programmer    masters
6      Google      sales executive    masters
7      Google  computer programmer  bachelors
8      Google     business manager  bachelors
9      Google     business manager    masters
10  Microsoft      sales executive  bachelors
11  Microsoft      sales executive    masters
12  Microsoft     business manager  bachelors
13  Microsoft     business manager    masters
14  Microsoft  computer programmer  bachelors
15  Microsoft  computer programmer    masters

In [17]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
encoded_company = LabelEncoder()
encoded_job = LabelEncoder()
encoded_degree = LabelEncoder()

In [21]:
features["company_n"] = encoded_company.fit_transform(features["company"])
features["job_n"] = encoded_job.fit_transform(features["job"])
features["degree_n"] = encoded_degree.fit_transform(features["degree"])

In [22]:
features

      company                  job     degree  company_n  job_n  degree_n
0        Meta      sales executive  bachelors          1      2         0
1        Meta      sales executive    masters          1      2         1
2        Meta     business manager  bachelors          1      0         0
3        Meta     business manager    masters          1      0         1
4        Meta  computer programmer  bachelors          1      1         0
5        Meta  computer programmer    masters          1      1         1
6      Google      sales executive    masters          0      2         1
7      Google  computer programmer  bachelors          0      1         0
8      Google     business manager  bachelors          0      0         0
9      Google     business manager    masters          0      0         1
10  Microsoft      sales executive  bachelors          2      2         0
11  Microsoft      sales executive    masters          2      2         1
12  Microsoft     business manager  bachelors          2      0         0
13  Microsoft     business manager    masters          2      0         1
14  Microsoft  computer programmer  bachelors          2      1         0
15  Microsoft  computer programmer    masters          2      1         1

In [27]:
new_features = features.drop(['company','job','degree'],axis='columns')
new_features

    company_n  job_n  degree_n
0           1      2         0
1           1      2         1
2           1      0         0
3           1      0         1
4           1      1         0
5           1      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          2      2         0
11          2      2         1
12          2      0         0
13          2      0         1
14          2      1         0
15          2      1         1

In [29]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [30]:
model.fit(new_features, target)

DecisionTreeClassifier()

In [31]:
model.score(new_features, target)

1.0

### Test: Check Row 6 [0,2,1] if it's predict salary less or more than 100k

In [33]:
model.predict([[0,2,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

Predict Result: Matched!

### Test: Check Row 10 [2,2,0] if it's predict salary less or more than 100k

In [34]:
model.predict([[2,2,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

Predict Result: Matched!